include:
    - remote: https://gitlab.roqs.basf.net/appstore/cicd/security/-/raw/main/.gitlab-ci.yml
    - remote: https://gitlab.roqs.basf.net/appstore/cicd/deploy/-/raw/main/.gitlab-ci.yml

stages:
    - compile
    - build
    - test_build
    - security
    - deploy
    - undeploy

variables:
    IMAGE_NAME: weather4fr
    DEPLOYMENT_NAME: weather4fr
    CI_REGISTRY: registry.roqs.basf.net
    IMAGE_NAME_LATEST: ${CI_REGISTRY}/${CI_REGISTRY_NAMESPACE}/${IMAGE_NAME}:latest
    IMAGE_NAME_NUMBERED: ${CI_REGISTRY}/${CI_REGISTRY_NAMESPACE}/${IMAGE_NAME}:${CI_PIPELINE_ID}

next_build:
    stage: build
    tags:
        - docker
    script:
        - cat "${next_env}" > .env
        - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_TOKEN} ${CI_REGISTRY}
        - docker build -t $IMAGE_NAME_NUMBERED .
        - docker push $IMAGE_NAME_NUMBERED
        - docker tag $IMAGE_NAME_NUMBERED $IMAGE_NAME_LATEST
        - docker push $IMAGE_NAME_LATEST
    interruptible: true

npm_audit:
    # allow_failure: true
    stage: security
    image: ${CI_REGISTRY}/base-images/node:latest
    tags:
        - docker
    script:
        - npm config set registry https://registry.npmjs.org/
        - npm audit --audit-level=moderate --package-lock-only
    interruptible: true
