apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    labels:
        app: weather4fr
    name: weather4fr-data
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 4Gi
    selector:
        matchLabels:
            app: weather4fr
            type: data
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: weather4fr
spec:
    replicas: 1
    selector:
        matchLabels:
            app: weather4fr
    template:
        metadata:
            labels:
                app: weather4fr
        spec:
            containers:
                - image: registry.roqs.basf.net/weather4fr/weather4fr
                  name: next
                  ports:
                      - containerPort: 5000
                  resources:
                      limits:
                          memory: 500Mi
                      requests:
                          memory: 100Mi
                  securityContext:
                      runAsGroup: 101
                      runAsUser: 100
            volumes:
                - name: weather4fr-data
                  persistentVolumeClaim:
                      claimName: weather4fr-data
